[2024-04-29T16:13:48.632+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T16:13:48.712+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:12:41.744633+00:00 [queued]>
[2024-04-29T16:13:48.725+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:12:41.744633+00:00 [queued]>
[2024-04-29T16:13:48.726+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T16:13:48.759+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): dump_data> on 2024-04-29 09:12:41.744633+00:00
[2024-04-29T16:13:48.765+0700] {standard_task_runner.py:63} INFO - Started process 49085 to run task
[2024-04-29T16:13:48.770+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'dump_data', 'manual__2024-04-29T09:12:41.744633+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmpnp6wbm9y']
[2024-04-29T16:13:48.771+0700] {standard_task_runner.py:91} INFO - Job 7: Subtask dump_data
[2024-04-29T16:13:48.854+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:12:41.744633+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T16:13:48.999+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='dump_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:12:41.744633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T09:12:41.744633+00:00'
[2024-04-29T16:13:49.001+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T16:13:49.003+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T16:13:49.004+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py", line 67, in dump
    raw_news.to_csv(f'{ROOT_PATH}/data/test/csv/vnexpress.csv')
NameError: name 'raw_news' is not defined
[2024-04-29T16:13:49.032+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=ETL-VNExpress, task_id=dump_data, execution_date=20240429T091241, start_date=20240429T091348, end_date=20240429T091349
[2024-04-29T16:13:49.068+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task dump_data (name 'raw_news' is not defined; 49085)
[2024-04-29T16:13:49.104+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T16:13:49.137+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T16:13:49.162+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
