[2024-05-23T15:54:15.036+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T15:54:15.122+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_load manual__2024-05-23T08:48:06.281897+00:00 [queued]>
[2024-05-23T15:54:15.136+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_load manual__2024-05-23T08:48:06.281897+00:00 [queued]>
[2024-05-23T15:54:15.137+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-23T15:54:15.197+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load> on 2024-05-23 08:48:06.281897+00:00
[2024-05-23T15:54:15.203+0700] {standard_task_runner.py:63} INFO - Started process 4536 to run task
[2024-05-23T15:54:15.208+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'transform_load', 'manual__2024-05-23T08:48:06.281897+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmp5ffb8nwj']
[2024-05-23T15:54:15.209+0700] {standard_task_runner.py:91} INFO - Job 22: Subtask transform_load
[2024-05-23T15:54:15.285+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.transform_load manual__2024-05-23T08:48:06.281897+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-05-23T15:54:15.442+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='transform_load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T08:48:06.281897+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T08:48:06.281897+00:00'
[2024-05-23T15:54:15.444+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T15:54:16.941+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:68 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-23T15:54:16.950+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:70 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-23T15:54:24.012+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T15:54:24.014+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py", line 83, in transform_load
    for topic in tqdm(os.listdir(PROCESSED_FOLDER)):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/Programming/Vietnamese-Text-Generator//data/test/processed'
[2024-05-23T15:54:24.087+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=ETL-VNExpress, task_id=transform_load, execution_date=20240523T084806, start_date=20240523T085415, end_date=20240523T085424
[2024-05-23T15:54:24.120+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task transform_load ([Errno 2] No such file or directory: '/mnt/d/Programming/Vietnamese-Text-Generator//data/test/processed'; 4536)
[2024-05-23T15:54:24.161+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T15:54:24.228+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T15:54:24.263+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
