[2024-04-29T16:29:11.174+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T16:29:11.252+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:28:00.114395+00:00 [queued]>
[2024-04-29T16:29:11.265+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:28:00.114395+00:00 [queued]>
[2024-04-29T16:29:11.266+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T16:29:11.298+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): dump_data> on 2024-04-29 09:28:00.114395+00:00
[2024-04-29T16:29:11.304+0700] {standard_task_runner.py:63} INFO - Started process 53357 to run task
[2024-04-29T16:29:11.309+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'dump_data', 'manual__2024-04-29T09:28:00.114395+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmp2nwl84e6']
[2024-04-29T16:29:11.311+0700] {standard_task_runner.py:91} INFO - Job 10: Subtask dump_data
[2024-04-29T16:29:11.390+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.dump_data manual__2024-04-29T09:28:00.114395+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T16:29:11.541+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='dump_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:28:00.114395+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T09:28:00.114395+00:00'
[2024-04-29T16:29:11.544+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T16:29:11.545+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T16:29:11.546+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py", line 70, in dump
    self.raw_news.to_csv(f'{ROOT_PATH}/data/test/csv/vnexpress.csv')
AttributeError: 'NoneType' object has no attribute 'to_csv'
[2024-04-29T16:29:11.568+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=ETL-VNExpress, task_id=dump_data, execution_date=20240429T092800, start_date=20240429T092911, end_date=20240429T092911
[2024-04-29T16:29:11.599+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task dump_data ('NoneType' object has no attribute 'to_csv'; 53357)
[2024-04-29T16:29:11.643+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T16:29:11.688+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T16:29:11.706+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
